stages:          
  - build
  - test
  - migrations
  - deploy

before_script:
  - echo "CONFIG_PATH=$CONFIG_PATH" > .env
  - echo "APP_ENV=$APP_ENV" >> .env
  - echo "SERVER_PORT=$SERVER_PORT" >> .env
  - echo "EMAIL_ADDRESS=$EMAIL_ADDRESS" >> .env
  - echo "EMAIL_PASSWORD=$EMAIL_PASSWORD" >> .env
  - echo "GOOSE_DRIVER=$GOOSE_DRIVER" >> .env
  - echo "GOOSE_DBSTRING=$GOOSE_DBSTRING" >> .env
  - echo "GOOSE_MIGRATIONS_DIR=$GOOSE_MIGRATIONS_DIR" >> .env
  - echo "MIGRATIONS_PATH=$MIGRATIONS_PATH" >> .env
  - echo "TELEGRAM_BOT_TOKEN=$TELEGRAM_BOT_TOKEN" >> .env
  - echo ".env file generated"

build-job:      
  stage: build
  script:
    - docker build -t ifall-image .

test-job:
  stage: test
  script:
    - docker run --rm ifall-image go test ./... -v -cover

migrations-job:  
  stage: migrations   
  script:
    - docker-compose run --rm migrate up

deploy-job:      
  stage: deploy  
  script:
    - docker-compose up -d ifall 
