services:
  ifall:
    image: ifall-image:latest
    env_file:
      - .env
    volumes:
      - ./logs/:/logs/
      - ./storage:/storage
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    networks:
      - app-network
    stop_grace_period: 5s

  migrate:
    image: ifall-image:latest
    env_file:
      - .env
    volumes:
      - ./storage:/storage
    entrypoint: ["goose", "-dir", "/migrations"]
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    external: false