// Code generated by MockGen. DO NOT EDIT.
// Source: client.go

// Package mock_client is a generated GoMock package.
package mock_client

import (
	models "iFall/internal/domain/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockApiClient is a mock of ApiClient interface.
type MockApiClient struct {
	ctrl     *gomock.Controller
	recorder *MockApiClientMockRecorder
}

// MockApiClientMockRecorder is the mock recorder for MockApiClient.
type MockApiClientMockRecorder struct {
	mock *MockApiClient
}

// NewMockApiClient creates a new mock instance.
func NewMockApiClient(ctrl *gomock.Controller) *MockApiClient {
	mock := &MockApiClient{ctrl: ctrl}
	mock.recorder = &MockApiClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApiClient) EXPECT() *MockApiClientMockRecorder {
	return m.recorder
}

// GetIPhoneData mocks base method.
func (m *MockApiClient) GetIPhoneData(id string) (*models.IPhone, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIPhoneData", id)
	ret0, _ := ret[0].(*models.IPhone)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIPhoneData indicates an expected call of GetIPhoneData.
func (mr *MockApiClientMockRecorder) GetIPhoneData(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIPhoneData", reflect.TypeOf((*MockApiClient)(nil).GetIPhoneData), id)
}
